server:
  port: 8001
  connection-timeout: 5000ms
spring:
  application:
    name: RPC-requester
  # 数据源配置
  datasource:
    url: jdbc:mysql://119.23.214.198:3306/nowander?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: nowander_user
    password: baotamysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# Dubbo 配置文件
dubbo:
  application:
    name: dubbo-requester
  registry:
    address: N/A
    register: false
  protocol:
    host: 127.0.0.1
    port: 18001
    name: dubbo
